.gitignore & HelloWorld (Kotlin/Maven) hinzugefügt
yddaPyo/Info-Klausur pull request #3
Opened 2017-08-02 22:35 UTC by archdtd111

Keine Ahnung obs richtig ist oder nicht. Ich war verbissen darauf jetzt noch was zu arbeiten.
Die .gitignore's habe ich mir ausm Internet gezogen und die Maven/Kotlin-Datei habe ich einfach mal erstellt. Musste bisschen was in den Settings ändern damit das lief.
Schaut es euch mal an.
Hab auch einfach irgendwas an der pom.xml gemacht...es ist spät und meine Birne platzt :D

2017-08-03 06:02 UTC, nipafx requested changes
Jeder Pull Request sollte sich auf ein Ticket beziehen - dieser hier geht zwei an. Bitte achte in Zukunft darauf. Jetzt können wir das so lassen, aber es muss noch einiges getan werden, damit der PR in Ordnung ist - siehe Kommentare.

Zur Inspiration kannst du in [die POM unseres Energy Models](https://github.com/nicolaiparlog/energy-model/blob/master/pom.xml) gucken. Du kannst auch selber testen ob alles funktioniert: Nach `mvn clean install` sollte `java -jar target/${project-jar}` "Hello, World!" auf die Kommandozeile schreiben.

2017-08-03 06:02 UTC, nicolaiparlog commented on .gitignore
> +#IntelliJ IDEA
Die hast du mit IntelliJ erstellt oder? Eigentlich eine gute Idee, aber mir gefällt nicht, dass nicht einfach der gesamte `.idea`-Ordner ausgeschlossen wird. Trag den bitte noch manuell ein. Ebenso sollten `iml`-Dateien ausgeschlossen werden.

2017-08-03 06:02 UTC, nicolaiparlog commented on .idea/compiler.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Der `.idea`-Order sollte nicht ins Repository und muss aus dem PR entfernt werden.

2017-08-03 06:02 UTC, nicolaiparlog commented on Info-Klausur.iml
> +<?xml version="1.0" encoding="UTF-8"?>
Diese Datei sollte nicht ins Repository und muss aus dem PR entfernt werden.

2017-08-03 06:02 UTC, nicolaiparlog commented on pom.xml
> +            <artifactId>kotlin-stdlib-js</artifactId>
Wir machen kein JavaScript, d.h. dieser `<dependency>`-Block kann raus.

2017-08-03 06:02 UTC, nicolaiparlog commented on pom.xml
> +            <artifactId>kotlin-stdlib-jre8</artifactId>
Das steht oben schon mal.

2017-08-03 06:02 UTC, nicolaiparlog commented on pom.xml
> +                            <goal>js</goal>
Diese Zeile kann raus.

2017-08-03 06:02 UTC, nicolaiparlog commented on .gitignore
> +target/
Der `target`-Folder wird zwar ausgeschlossen, aber du hast dennoch ein paar Dateien darin in diesem PR. Die müssen wieder raus.

2017-08-03 06:02 UTC, nicolaiparlog commented on pom.xml
> +                    <execution>
Für die Tests gibt es ein eigenes Issue, bitte nimm diesen `<execution>` Block erstmal wieder raus.

2017-08-03 06:02 UTC, nicolaiparlog commented on pom.xml
> +            <artifactId>kotlin-test</artifactId>
Wir arbeiten nicht mit `kotlin-test` sondern mit JUnit (das kommt aber in einem separaten Issue rein).

2017-08-03 06:02 UTC, nicolaiparlog commented on pom.xml
> +        </plugins>
Das `maven-assembly-plugin` muss noch konfiguriert werden, damit eine ausführbare JAR rauskommt.

2017-08-03 06:02 UTC, nicolaiparlog commented on src/Kotlin/Hello, World!.kt
> +/**
Quelltext gehört in `src/main/kotlin`, nicht `src/Kotlin`. Und tu dir selber einen gefallen und nimm Dateinamen ohne Leer- und Sonderzeichen. :wink:

2017-08-03 08:44 UTC, archdtd111 commented on .gitignore
> +#IntelliJ IDEA
@zvenon  Die hier

2017-08-03 09:00 UTC, archdtd111 commented on src/Kotlin/Hello, World!.kt
> +/**
Haken

2017-08-03 12:06 UTC, archdtd111 commented
Hallo Nicolai,

habe jetzt an ein zwei Sachen gearbeitet und auf meinen Fork hochgeladen.
Wollte jetzt einen neuen PR machen um quasi meinen Fork (HEAD) mit dem  
Base Fork (yddaPyo/Info-Klausur) zu mergen.
Aber da wird mir keine Möglichkeit angezeigt den PR zu machen. Also  
nicht mal ein
Button oder so ähnliches.
Im Anhang ein Screenshot.

Mit freundlichen Grüßen,

Artur \,,/

2017-08-03 12:14 UTC, nicolaiparlog commented
Die Nachricht hat keinen Anhang. Falls du sie als E-Mail verfasst hast, ging die an GitHub und der Anhang wird dann (anscheinend) ignoriert.

2017-08-03 18:12 UTC, nicolaiparlog commented
Ok, hab den Anhang in der Mail bekommen. Ich füge ihn mal hier ein.

:bulb: Wenn du einen Kommentar verfasst, steht am unteren Ende wie man Dateien anhängt
![fuernicolai](https://user-images.githubusercontent.com/6537432/28936465-1f3b62c2-7888-11e7-84ce-1c2464ac1b53.png)
.

2017-08-03 18:18 UTC, nicolaiparlog commented
> habe jetzt an ein zwei Sachen gearbeitet und auf meinen Fork hochgeladen.

[Hier](https://github.com/archdtd111/Info-Klausur/commits/master) siehst du welche Commits in deinem Fork auf `master` sind - der jüngste ist fdd01584.

> Wollte jetzt einen neuen PR machen um quasi meinen Fork (HEAD) mit dem Base Fork (yddaPyo/Info-Klausur) zu mergen.

Man kann keine Forks mergen, sondern nur Branches. Ich vermute, dass du das meinst - ist aber wichtig, dass du die richtigen Worte benutzt.

> Aber da wird mir keine Möglichkeit angezeigt den PR zu machen.

Sieht für mich so aus als würde GitHub dich darauf hinweisen, dass es bereits einen Pull Request zwischen den beiden Branches gibt. Stimmt auch, diesen hier.

Bestehende PRs kannst du einfach erweitern, indem du weitere Commits auf den Source Branch pusht. Und das ist auch schon passiert: Guck mal direkt über deinem Kommentar, auf den ich hier antworte. Da taucht genau der jüngste Commit (fdd015) auf.

2017-08-04 07:32 UTC, nicolaiparlog commented on .gitignore
> +target/
Hier gab es ein Missverständnis: Die `target/` Zeile war richtig. Aber die Dateien in dem Ordner, die Teil dieses Pull Requests sind, sind fehl am Platze.

Du hast bisher die (korrekte) Zeile rausgenommen und die (überflüssigen) Dateien dringelassen.

2017-08-04 07:33 UTC, nicolaiparlog commented
Damit die zugeklappte Nachricht nicht untergeht [hier ein Link dorthin](https://github.com/yddaPyo/Info-Klausur/pull/3#discussion_r131328665).

2017-08-04 07:38 UTC, archdtd111 commented
Ich habe es schon so gemeint wie ich es ausgedrückt habe.
Mein Problem ist, ich habe meinen Fork aktualisiert, dh, dort sind alle 
Neuerungen die ich lokal gemacht habe schon drauf gepusht.
Habe alle Änderungen lokal über den Master gemacht. Also wenn ich jetzt 
von meiner Lokalen auf das usprüngliche Projek upstreame, dann wird es 
ja automatisch aktualisiert und ich kann das nicht über einen PR 
managen.

Greetings,

Artur


Am 2017-08-03 20:18, schrieb Nicolai Parlog:
>> habe jetzt an ein zwei Sachen gearbeitet und auf meinen Fork
>> hochgeladen.
> 
> Hier [1] siehst du welche Commits in deinem Fork auf master sind - der
> jüngste ist fdd0158 [2].
> 
>> Wollte jetzt einen neuen PR machen um quasi meinen Fork (HEAD) mit
>> dem Base Fork (yddaPyo/Info-Klausur) zu mergen.
> 
> Man kann keine Forks mergen, sondern nur Branches. Ich vermute, dass
> du das meinst - ist aber wichtig, dass du die richtigen Worte benutzt.
> 
>> Aber da wird mir keine Möglichkeit angezeigt den PR zu machen.
> 
> Sieht für mich so aus als würde GitHub dich darauf hinweisen, dass
> es bereits einen Pull Request zwischen den beiden Branches gibt.
> Stimmt auch, diesen hier.
> 
> Bestehende PRs kannst du einfach erweitern, indem du weitere Commits
> auf den Source Branch pusht. Und das ist auch schon passiert: Guck mal
> direkt über deinem Kommentar, auf den ich hier antworte. Da taucht
> genau der jüngste Commit (fdd015) auf.
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [3], or mute the
> thread [4].
> 
> 	*
> 
> Links:
> ------
> [1] https://github.com/archdtd111/Info-Klausur/commits/master
> [2]
> https://github.com/yddaPyo/Info-Klausur/commit/fdd015845a2c69211c89ee3267983e355b98449b
> [3] 
> https://github.com/yddaPyo/Info-Klausur/pull/3#issuecomment-320049511
> [4]
> https://github.com/notifications/unsubscribe-auth/AdIrOOOgQCrdZUo2UZAQByKn8JGF_o0gks5sUg8BgaJpZM4OrvnQ

2017-08-04 08:45 UTC, nicolaiparlog commented
> Ich habe es schon so gemeint wie ich es ausgedrückt habe.

Beziehst du dich hierauf?

> wollte jetzt einen neuen PR machen um quasi meinen Fork (HEAD) mit dem Base Fork (yddaPyo/Info-Klausur) zu mergen

Das geht nicht, man kann keine Forks mergen. Die Konzepte _Fork_ (ein ganzes Git Repository mit Branches, Tags, etc) und _Merge_ (eine Aktivität zwischen zwei Branches) ergeben zusammen keinen Sinn. 

> Also wenn ich jetzt von meiner Lokalen auf das usprüngliche Projek upstreame, dann wird es ja automatisch aktualisiert und ich kann das nicht über einen PR managen.

Wenn du mit "ursprüngliches Projekt" dieses hier und nicht deinen Form meinst, ist das richtig. Deswegen sieht der normale Arbeitsprozess vor, ein Projekt zu forken und dann den Fork zu klonen, so dass der Fork als _origin_ Remote verwendet wird. Zusätzlich kann man dann noch das Originalprojekt als _upstream_ Remote hinzufügen, aber davon pullt man üblicherweise nur.

Was gibt denn `git remote -v` aus?

2017-08-04 08:51 UTC, nicolaiparlog commented on .gitignore
> +=======
Das hier sind die Überreste eines [Merge Conflicts](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/). Der Block über `===` bis zum `<<<` war auf deinem Branch und der darunter bis zum `>>>` kam von `pomxml` (ich glaube das war sorum, vergesse das immer) - Git konnte sie nicht automatisch zusammenführen, also musst du das manuell machen. Git müsste dich dabei auch hingewiesen haben.

Du kannst dir entweder einen der beiden Blöcke aussuchen oder ein Mischmasch erstellen. In jedem Fall sollte nachher jede Zeile nur einmal da sein und die `<<<`, `===`, `>>>` Zeilen sollten raus sein.

2017-08-04 08:57 UTC, nicolaiparlog commented
Vielleicht ist es einfacher noch einmal von vorne anzufangen. Du könntest das hier machen:

* kopier den gesamten Projektordner irgendwohin, damit du deine Arbeit nicht verlierst
* setz deinen `master` Branch auf den Zustand zurück, den du [in diesem Repsoitory siehst](https://github.com/yddaPyo/Info-Klausur/commits/master) - wenn du mir den Output von `git remote -v` gibst, kann ich dir dabei helfen
* fang einen neuen Branch von `master` an
* erstelle `.gitignore` (einen ersten Draft kannst du aus der Kopie des Projekts kopieren)
* commit, push, neuen Pull Request eröffnen
* dann zurück zu `master` (wichtig!)
* neuen Branch anfangen und an der Arbeit mit der POM beginnen (einen ersten Draft kannst du aus der Kopie des Projekts kopieren)
* ⚠️ in dem Branch gibt es dann noch keine `.gitignore`, d.h. du musst aufpassen, keine IntelliJ oder Maven Ordner/Dateien zu committen
* commit, push, neuen Pull Request eröffnen

2017-08-07 11:59 UTC, nicolaiparlog commented
Ich glaube #5 und #10 machen diesen Pull Request unnötig und ihr könnt ihn schließen (nicht mergen!).

2017-08-07 12:49 UTC, closed without merging